version: "3.8"

services:

  consul:
    image: hashicorp/consul
    command: agent -dev -client=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "consul", "info"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - devpro

  postgres:
    image: postgres:16-alpine
    container_name: postgres-devpro
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - devpro

  adminer:
    image: adminer:latest
    container_name: adminer-devpro
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - devpro

  redis:
    image: redis:7.2-alpine
    container_name: devpro-redis
    restart: unless-stopped
    command: >
      redis-server
      --notify-keyspace-events Ex
      --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - devpro

  api-gateway:
    build: ./api-gateway
    container_name: devpro-api-gateway
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - devpro

  #  Traefik Reverse Proxy
  traefik:
    image: traefik:v3.6
    container_name: devpro-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devpro

  #  Shared DBs for user code execution
  problem-postgres:
    image: postgres-common
    container_name: problem-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - devpro

  problem-mongodb:
    image: mongodb-common
    container_name: problem-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    networks:
      - devpro

  user-service:
    build: ./user-service
    container_name: devpro-user-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - devpro

  problem-service:
    build: ./problem-service
    container_name: devpro-problem-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - devpro

  code-runner-service:
    build: ./code-runner-service
    container_name: devpro-code-runner
    restart: unless-stopped
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      consul:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workdir:/app/workdir
    networks:
      - devpro

networks:
  devpro:
    driver: bridge