spring:
  application:
    name: code-runner-service
  cloud:
    consul:
      port: 8500
      host: ${CONSUL_HOST:localhost}
      discovery:
        register: true
        instance-id: ${spring.application.name}-${server.port}
        prefer-ip-address: true

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}

#port
server:
  port: 8083
  max-http-request-header-size: 64KB


#consul client

#health check
management:
  endpoints:
    web:
      exposure:
        include: health, info


admin:
  service:
    key: ${ADMIN_SERVICE_KEY}

#user id header
headers:
  user:
    id: ${USER_ID_HEADER}

#rate limiting
limits:
  user: ${MAX_REQUEST_PER_USER} #per minute
  global:
    req: ${MAX_GLOBAL_REQ}
    time: ${GLOBAL_SEC}

#proxy host for traefik
traefik:
  domain: ${DOMAIN}
  network: ${NETWORK:devpro-network}
  protocol: ${PROTOCOL:http}